### ISSUE TITLE
build fails if not global is defined

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#104]
```
---                                                                              
global:                                                                          
                                                                                 
bootstrap:                                                                       
  - step:                                                                        
    - microstep:                                                                 
      - exec_local: echo A                                                       
                                                                                 
setup:                                                                           
                                                                                 
export: 
```
gives:
```
$kameleon build test.yaml
Error : undefined method `keys' for nil:NilClass
Unfortunately, a fatal error has occurred : undefined method `keys' for nil:NilClass.
Use --debug option for more details
```
while:
```
---                                                                              
global:                                                                          
  var: 1                                                                         
bootstrap:                                                                       
  - step:                                                                        
    - microstep:                                                                 
      - exec_local: echo A                                                       
                                                                                 
setup:                                                                           
                                                                                 
export:
```
gives:
```
$ kameleon build test.yaml
Creating kameleon build directory : /home/neyron/scm/OAR/kameleon-recipes/build/test
Starting build recipe 'test.yaml'
Step _init_bootstrap took: 0 secs
Step 1 : bootstrap/step/microstep
--> Running the step...
Starting command: "bash"
[local] The local_context has been initialized
[local] A
Step step took: 1 secs
Step _clean_bootstrap took: 0 secs
Step _init_setup took: 0 secs
Step _clean_setup took: 0 secs
Step _init_export took: 0 secs
Step _clean_export took: 0 secs

Successfully built 'test.yaml'
Total duration : 1 secs
```
