### ISSUE TITLE
rescue does not behave the same if used at the root of the step or in a microstep

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#105]
```
---                                                                              
global:                                                                          
  var: 1                                                                         
bootstrap:                                                                       
  - step:                                                                        
    - rescue:                                                                    
      - exec_local: exit 1                                                       
      - exec_local: echo "failed in the root of the step"                        
    - microstep:                                                                 
      - rescue:                                                                  
        - exec_local: exit 1                                                     
        - exec_local: echo "failed in the microstep"                             
                                                                                 
setup:                                                                           
                                                                                 
export: 
```
gives:

```
$ kameleon build test.yaml
Creating kameleon build directory : /home/neyron/scm/OAR/kameleon-recipes/build/test
Starting build recipe 'test.yaml'
Step _init_bootstrap took: 0 secs
Step 1 : bootstrap/step/rescue
--> Running the step...
Starting command: "bash"
[local] The local_context has been initialized
Starting command: "bash"
Error occured when executing the following command :

> exec_local: exit 1
Press [r] to retry
Press [c] to continue with execution
Press [a] to abort execution
Press [l] to switch to local_context shell
Press [o] to switch to out_context shell
Press [i] to switch to in_context shell
answer ? [c/a/r/l/o/i]:  c
User choice: [c] continue
[local] failed in the root of the step
Step 2 : bootstrap/step/microstep
--> Running the step...
[local] failed in the microstep
Step step took: 3 secs
Step _clean_bootstrap took: 0 secs
Step _init_setup took: 0 secs
Step _clean_setup took: 0 secs
Step _init_export took: 0 secs
Step _clean_export took: 0 secs

Successfully built 'test.yaml'
Total duration : 3 secs
```
-> breakpoint for the 1st rescue, not for the 2nd.
