### ISSUE TITLE
Add possibility to write directly the step implementation in the recipe

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon#12]
All is in the title...
An example:

```
setup:
  - my_step:
    - my_var: 123
    - my_microstep:
      - exec_in: echo "hello world"
```
