### ISSUE TITLE
missing --- in generated file

### ISSUE THREAD

**Issue by bleuse** [oar-team/kameleon#123]
I'm using a step where I generate a file containing the sequence `---`.

The step code boils down to:
```yaml
- generate-file:
  - write_in:
    - $${location}/file
    - |
      some content for my file
      ---
      some injected value: $${key}
```

I expect the generated file to be (if `key` is set to e.g. `42`):
```
some content for my file
---
some injected value: 42
```

However, the generated content is (see the missing `---` sequence):
```
some content for my file

some injected value: 42
```

This seems to be related to the code managing steps ([step.rb](../blob/0c6556dd/lib/kameleon/step.rb)) where a `gsub` is performed to remove `---` no matter where it is located.
