### ISSUE TITLE
Build from cache failed with fatal error due to dynamically generated file

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon#38]
I have a step that generate a timestamp from local and put it to the recipe so I know when the build was done. Here is the step file:
```yaml
# Add Timestamp
- timestamping:
  - exec_local: date +%s > timestamp
  - local2in:
    - timestamp
    - /img_build_timestamp
```
The problem is when I build it from the cache using the ``--from-cache`` option I get:
```
Step 37 : setup/add_timestamp/timestamping
--> Running the step...
Redirecting pipe into cache
Persistent cache missing file
fatal error...
Waiting for cleanup before exiting...
Cleaning setup section
[in] Reading package lists...
[in] Building dependency tree...
[in] Reading state information...
[in] Reading package lists...
[in] Building dependency tree...
[in] Reading state information...
[in] 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[local] QEMU 2.1.2 monitor - type 'help' for more information
[local] (qemu) system_powerdown
[local] Waiting for qemu virtual machine to shutdown...(3s)  ~> Done
Cleaning export section
Failed to use persistent cache
```
I think it is a bug from the cache that look for a file that do not exist because it is dinamically generated.
