### ISSUE TITLE
add generic contexts

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon#4]
To be independent from underlying interpreter (bash, python, ruby, powershell...), the context declaration variables like `workdir` should be remove and replace by an inline command like:

```
bash -c "cd /tmp && bash"
```

It will be a good idea to enable generic context definition linked to the exec_\* command. For example:

```
# in recipe
global:
  context:
    - my_ctx: bash -c "cd /tmp && bash"

# in steps
- my_step:
  - exec_my_ctxt: echo "Hello :-)"
```
