### ISSUE TITLE
Attached data documentation

### ISSUE THREAD

**Issue by SalemHarrache** [oar-team/kameleon#41]

**Comment by mickours** [comment]
As a reminder, you can use file that are stored in ``steps/data/`` of your recipe or a recipe you extends with the built-in variable ``$$kameleon_data_dir``.

For example:
```yaml
- configure_bashrc:
  - local2in:
    - $$kameleon_data_dir/skel/.bashrc
    - /etc/skel/.bashrc
```
