### ISSUE TITLE
Best way to pass environement variable to a context (for proxy settings)

### ISSUE THREAD

**Issue by mickours** [oar-team/kameleon#49]
Hi,

I'm using Kameleon behind a proxy and I have to set the `http_proxy` env variable in all my context.

What is the best way to do this?

For now I put my proxy settings directly in the `default/base/bashrc` file but I would like to extend it some way without touching the base template.

Thanks,
Michael

**Comment by SalemHarrache** [comment]
Hi @mickours, 

The best way to interact in Bash with context is to use the ``env`` section.

Each file in this section will be sourced to the initialization of each context. It allows you, among other things, to use advanced bash functions, but you could also set environment variables such as HTTP_PROXY, etc.


Here is a little example :

`example_env_recipe.yaml`:
```
env:
  - enable_http_proxy

setup:
  - macrostep:
    - microstep:
      - exec_local: echo $HTTP_PROXY
      - exec_out: echo $HTTP_PROXY
      - exec_in: echo $HTTP_PROXY
```


`steps/env/enable_http_proxy`:
```
export HTTP_PROXY=http://10.0.8.1:3128
```

```
$ kameleon build simple_recipe.yaml

...

--> Running the step...
[local] http://10.0.8.1:3128
Starting process: "/bin/bash"
[out] The out_context has been initialized
[out] http://10.0.8.1:3128
Starting process: "/bin/bash"
[in] The in_context has been initialized
[in] http://10.0.8.1:3128


...
```

This should answer your question ;-)

Have a nice day,
Salem
