### ISSUE TITLE
Variable substitution does not work if followed with a dash?

### ISSUE THREAD

**Issue by npf** [oar-team/kameleon#76]
I get:
```
kameleon-bootstrap-recipes (foreign_arch_crossbuild *$%)$ kameleon build qemu/debian7.yaml
Error : /home/neyron/scm/kameleon-bootstrap-recipes/qemu/debian7.yaml: variable $$arch-live not found in local or global
```
Which comes from having:
```
global:
  arch: x86_64
  iso_arch: $$arch
```
and then
```
    iso_filename: debian-jessie-$${iso_arch}-live.iso 
```
It works ok if I set iso_arch directly: 
```
  iso_arch: x86_64
```

**Comment by npf** [comment]
It seems that the issue could be easily resolved by forcing any variable to always use braces.

No more $$var, but always $${{var}}

?

**Comment by npf** [comment]
@SalemHarrache @mickours : any news on that issue ?
Could we fix it before releasing v2.7.3 ?

**Comment by mickours** [comment]
no, we have to work on this.

**Comment by mickours** [comment]
I not able to reproduce, can you provide a simple case?

**Comment by SalemHarrache** [comment]
Hi.
Here is an example

`recipe.yaml`
```
global:
    arch: x86_64
    iso_arch: $$arch
    iso_filename: debian-jessie-$${iso_arch}-live.iso 


bootstrap:
    - test:
      - step:
        - exec_local: echo $$iso_filename
        - exec_local: echo $${iso_filename}
```

```
$ kameleon build 
Error : /tmp/2016-04-25-10-58-28_6pg/recipe.yaml: variable $$arch-live not found in local or global
```

We must always resolve nested variables by adding braces.

This :
```
debian-jessie-$${iso_arch}-live.iso  --> debian-jessie-$${arch}-live.iso
```
instead of...
```
debian-jessie-$${iso_arch}-live.iso  --> debian-jessie-$$arch-live.iso
```
