### ISSUE TITLE
Environment variables lost in context_in

### ISSUE THREAD

**Issue by FlorianPO** [oar-team/kameleon#86]
Under certain conditions, environment variables set in context_in can be lost.

This is fine ($test_var is known) :

```
setup:
  - first_step:
    - bloc1:
      - exec_in: export test_var="test"
      - exec_in: echo $test_var
```

This is not fine ($test_var is unknown) :

```
setup:
  - first_step:
    - bloc1:
      - exec_in: export test_var="test"
    - bloc2:
      - exec_in: echo $test_var
```

This could be related to #64
